_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.9.22
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 3
                - 16
                - 23
                - 55
                - 61
            "4": 3.9.22
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
D:
    value: 192
batch_files:
    value: 4
beta_l1:
    value: 5
gamma:
    value: 16
k:
    value: 3072
lambda_orth:
    value: 0.01
lr:
    value: 0.0003
num_epochs:
    value: 10
